version: '3'
services:
  app:
    container_name: golang-app
    build: .
    # command: go run main.go
    command: fresh
    volumes:
      - ./dive-into-go:/go/src/github.com/dykyi-roman/dive-into-go
    working_dir: /go/src/github.com/dykyi-roman/dive-into-go
    ports:
      - "8080:${GO_PORT}"
      - "2345:2345"
    environment:
      GO_PORT: ${GO_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - redis-net
    depends_on:
      - redis
      - db
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'      
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'      
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'      
    ports:      
      - '3307:3306'
    expose:      
      - '3306'      
    volumes:
      - my-db:/var/lib/mysql
networks:
  redis-net:

volumes:
  redis-data:      
  my-db: