version: '3'
services:
  app:
    container_name: golang-app
    build: .
    # command: go run main.go
    command: fresh
    volumes:
      - ./src:/go/src/github.com/dykyi-roman/dive-into-go
    working_dir: /go/src/github.com/dykyi-roman/dive-into-go
    ports:
      - "8080:${PORT}"
      - "2345:2345"
    environment:
      PORT: ${PORT}
